export default function Head() {
  return (
    <>
      <title>Next13 App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create react app" />
      <link rel="icon" href="/favicon.ico"/>
    </>
  )
}